### ISSUE TITLE
Feature Request - Firmware Status / Upgrade Available

### ISSUE THREAD

**Issue by Coolie1101** [colinodell/python-qnapstats#44]
Hi,
Would it be possible to get a Firmware Version and/or a Firmware Upgrade Available Sensor?

**Comment by colinodell** [comment]
This library already exposes whether a firmware update is available via the `get_firmware_update()` method.  Integrating this into HASS would need to be done in https://github.com/home-assistant/core.  Unfortunately, I am no longer have the bandwidth to maintain that integration or add new features (see #43), but anyone familiar with HASS development should be able to implement such a sensor and submit a pull request for that against the HASS core repo.

Because there's nothing further that needs to be done in this particular repository I'm going to close this issue.
