### ISSUE TITLE
Stopped working after QTS update to 4.5.4.1741

### ISSUE THREAD

**Issue by oywino** [colinodell/python-qnapstats#61]
Please provide the following information along with your issue report (replace anything inside of `<>`):

**Device Model Number**: TS-453Mini

**QTS Version**: 4.5.4.1741

If you're reporting a `KeyError`, please also provide the XML response from your QNAP device.  You can easily obtain this by running the `debug.py` script.

**XML/Debug Output:**

~~~
<Insert your XML or debug output here>
~~~
As the headline says, after updating QTS, qnapstats stopped working for my NAS. It was working perfectly for this NAS for a long time.  I have seen reports elsewhere from other users that indicates that qnapstats stopped working on all QNAP NAS models which were updated to 4.5.4.1741.  Is this a fact?  Is this integrations still being maintained? If so, will this be, or has this been fixed?

**Comment by colinodell** [comment]
Hi @oywino,

> I have seen reports elsewhere from other users that indicates that qnapstats stopped working on all QNAP NAS models which were updated to 4.5.4.1741. Is this a fact?

The only compatibility issue I'm aware of is #60.  Are you getting that same error or something different?

If it's something else and you could please provide an error message and/or stack trace for the issue you're seeing I'd greatly appreciate it!

> Is this integrations still being maintained?

The short answer is yes.  Please see #43 for more details.

> If so, will this be, or has this been fixed?

"this" depends directly on what the underlying error is.  We're only aware of #60, for which nobody has submitted a fix yet, but if there are other errors it would be very helpful to know what they are so that somebody can fix those too :)

**Comment by colinodell** [comment]
[Version 0.4.0](https://github.com/colinodell/python-qnapstats/releases/tag/0.4.0) was recently released with fixes for known issues on QTS 4.5.4.  Could you please try with that version?

If you are a Home Assistant user, please upgrade to Home Assistant Core version 2021.8.7 which also contains those fixes.

If the issues persist we will need a copy of the `debug.py` output to investigate this further.

**Comment by oywino** [comment]
I tested today by upgrading to 21.8.7 and it works ok now.
Thanks for your effort @colinodell 
It would be nice though, to know what QNAP did that broke the integration?

**Comment by colinodell** [comment]
Great! It sounds like the issue here was identical to #60.  QNAP basically changed how they expose the bandwidth information - they moved that data to a different URL that we needed to check instead.
